runtime: nodejs16
instance_class: F2

env_variables:
  NODE_ENV: production
  JWT_SECRET: "suaChaveSecreta"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto

# Configurações de segurança (opcional)
handlers:
- url: /.*
  script: auto
  secure: always
