runtime: nodejs16
entrypoint: app/index.js

env_variables:
  NODE_ENV: production
  JWT_SECRET: "testando123"
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always
